# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = LIUpdate
DESTDIR = ../bin
QT += core gui network
CONFIG += debug
DEFINES += QT_LARGEFILE_SUPPORT QT_NETWORK_LIB QT_DLL
INCLUDEPATH += ./GeneratedFiles \
    ./GeneratedFiles/Release \
    .
macx {
    LIBS += ./../comm/quazip/quazip/libmacquazip.a
    LIBS += -lz
}
!macx {
    LIBS += ./../comm/quazip/quazip/quazip.a
}
PRECOMPILED_HEADER = StdAfx.h
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/release
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(LIUpdate.pri)
