# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../LIWord0023/config.h \
    ../comm/LIFileDownload.h \
    ./stdafx.h \
    ./UpdateDialog.h \
    ../comm/global.h \
    ../comm/log.h \
    ../comm/ZipFile.h \
    ../comm/qtlockedfile/qtlockedfile.h \
    ../comm/qtsingleapplication/qtlocalpeer.h \
    ../comm/qtsingleapplication/qtsingleapplication.h \
    ../comm/qtsingleapplication/qtsinglecoreapplication.h
SOURCES += ../comm/LIFileDownload.cpp \
    ./main.cpp \
    ./stdafx.cpp \
    ./UpdateDialog.cpp \
    ../comm/global.cpp \
    ../comm/log.cpp \
    ../comm/ZipFile.cpp \
    ../comm/qtlockedfile/qtlockedfile.cpp \
    ../comm/qtsingleapplication/qtlocalpeer.cpp \
    ../comm/qtsingleapplication/qtsingleapplication.cpp \
    ../comm/qtsingleapplication/qtsinglecoreapplication.cpp

