# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------
TEMPLATE = app
TARGET = LIWord
DESTDIR = ../bin
QT += core gui sql network xml phonon webkit qaxserver qaxcontainer
CONFIG += debug
#CONFIG+=debug_and_release
DEFINES += QT_LARGEFILE_SUPPORT QT_XML_LIB QT_SQL_LIB QT_NETWORK_LIB QT_WEBKIT_LIB QT_PHONON_LIB

INCLUDEPATH += ./ChartDirector \
    ../../../../../workspace/c++/dependency/zlib-1.2.5/zlib-1.2.5 \
    ./../comm/quazip/quazip \
    ./GeneratedFiles \
    ./GeneratedFiles/Release \
    . \
    ./../comm \
    ./../comm/QtSpeech

macx {
    LIBS += ./../comm/quazip/quazip/libmacquazip.a
    LIBS += -lz
    HEADERS += ../comm/QtSpeech/QtSpeech.h
    SOURCES += ../comm/QtSpeech/QtSpeech_mac.cpp \
            SpeakWTTS.cpp
    HEADERS += SpeakWTTS.h
    LIBS += -framework AppKit
}


LIBS += -L"../comm" \
    -L"./../comm/ChartDirector/lib" -lchartdir


win32 {
    HEADERS += ../comm/QtSpeech/QtSpeech.h
    SOURCES += QtSpeech_win.cpp
}

unix:!mac {
    HEADERS += speaker.h
    SOURCES += speaker.cpp
    SOURCES +=


    # Linux: use asound
    LIBS += -lasound



    LIBS += ./../comm/quazip/quazip/quazip.a
    # Mac: use system Frameworks
    #LIBS += -framework CoreAudio -framework AudioUnit -framework AudioToolbox -framework Carbon
}

PRECOMPILED_HEADER = StdAfx.h
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/release
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(LIWord0030.pri)
win32:RC_FILE = LIWord0030.rc
