# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------
TEMPLATE = app
TARGET = LIWord
DESTDIR = ../bin
QT += core gui sql network xml phonon webkit qaxserver qaxcontainer
CONFIG += release
#CONFIG+=debug_and_release
DEFINES += QT_LARGEFILE_SUPPORT QT_XML_LIB QT_SQL_LIB QT_NETWORK_LIB QT_WEBKIT_LIB QT_PHONON_LIB

INCLUDEPATH += ./ChartDirector \
    ../../../../../workspace/c++/dependency/zlib-1.2.5/zlib-1.2.5 \
    ./../comm/quazip/quazip \
    ./GeneratedFiles \
    ./GeneratedFiles/Release \
    . \
    ./../comm \
    ./../comm/QtSpeech \
    "/usr/include/speech_tools" \
    "/usr/include/festival/"

LIBS += ./../../qt/comm/quazip/quazip/rquazip.a
LIBS += -L"../../qt/comm" \
    -lncurses \
    -L"festival" -lFestival \
    -L"speech_tools" -lestools -lestbase -leststring \
    -L"./../../qt/comm/ChartDirector/lib" -lchartdir \
    -lasound \
    -lncurses

PRECOMPILED_HEADER = StdAfx.h
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/release
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(LIWord0030.pri)
win32:RC_FILE = LIWord0030.rc


