# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./stdafx.h \
    ./UIGDialog.h \
    ../comm/global.h \
    ../comm/log.h
SOURCES += ./main.cpp \
    ./stdafx.cpp \
    ./UIGDialog.cpp \
    ../comm/global.cpp \
    ../comm/log.cpp
