######################################################################
# Automatically generated by qmake (2.00a) Wed Jun 22 16:57:14 2005
######################################################################

TEMPLATE = lib
CONFIG += qt warn_on staticlib
QT -= gui
#LIBS += -lz
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += *.h

SOURCES += *.c *.cpp

unix {
  OBJECTS_DIR=.obj
  MOC_DIR=.moc
}
macx {
    TARGET = macquazip
}

# UNIX installation

isEmpty(PREFIX): PREFIX=.

unix {
  headers.path=$$PREFIX/quazip
  headers.files=$$HEADERS
  target.path=$$PREFIX/lib
  INSTALLS += headers target
}
